name: Build and Deploy Programmatic-AI-TTD-UI To CloudRun
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy Image to Cloud Run
    runs-on: ubuntu-20.04
    env:
      SERVICE_NAME: ${{ secrets.SERVICE_NAME_NEW }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID}}
          export_default_credentials: true

      - name: Build Image
        run: |
          docker build -t asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
      - name: Gcloud Authentication
        run: |
          gcloud auth configure-docker -q
      - name: "Remove all container"
        run: |
          gcloud container images list-tags asia.gcr.io/$PROJECT_ID/$SERVICE_NAME  --format="get(digest)" --limit=1 --sort-by="timestamp"> tags && while read p; do gcloud container images delete "asia.gcr.io/$PROJECT_ID/$SERVICE_NAME@$p" --quiet --force-delete-tags; done < tags
      - name: Deploy Image to Container Registry
        run: |
          docker push asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
      - name: Deploy Cloud Run
        run: |
          gcloud --quiet beta run deploy $SERVICE_NAME --image asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
          --platform managed \
          --allow-unauthenticated \
          --cpu 4 \
          --memory 6G \
          --region us-east1 \
          --max-instances 10 \
          --port 8080 \
          --timeout 60m
